'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Globe2, Leaf, Menu, Sparkles, X } from 'lucide-react'

const topics = [
  { slug: 'art-crafts', title: 'Art & Crafts', ml: 'കലയും കരകൗശലവും', tagline: 'Hands shaped by heritage', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kerala%20mural%20painting.jpg', intro: 'From the gleam of Aranmula Kannadi to the rhythm of coir weaving, Kerala crafts carry living knowledge from one generation to the next.', highlights: [['Aranmula Kannadi', 'A handmade metal mirror whose polished surface reflects a centuries-old alloy craft.'], ['Coir craft', 'Coconut fibre becomes mats, baskets and objects shaped by Kerala’s coastal life.'], ['Wood & bell metal', 'Carving and casting bring temple forms, lamps and household vessels to life.']] },
  { slug: 'music', title: 'Music', ml: 'സംഗീതം', tagline: 'Where rhythm becomes ritual', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lGJhbWI30aidvlVNQUOKVKuXAztmiU.png', intro: 'Kerala’s soundscape moves from the intimate devotion of Sopana Sangeetham to the thunderous chenda ensembles of temple festivals.', highlights: [['Sopana Sangeetham', 'A devotional singing tradition performed near temple sanctums with measured, expressive melodies.'], ['Chenda melam', 'Layered percussion gives festivals their unmistakable pulse and collective energy.'], ['Temple instruments', 'Maddalam, kombu and kuzhal join ceremonial music across Kerala’s sacred spaces.']] },
  { slug: 'dance', title: 'Dance', ml: 'നൃത്തം', tagline: 'Stories painted in motion', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-8EW61BlJSlCIRtQQpdHH0oyBv21Trl.png', intro: 'Kerala’s dances are complete worlds of gesture, costume and story—from the expressive theatre of Kathakali to the circular grace of Thiruvathirakali.', highlights: [['Kathakali', 'A classical dance-drama where elaborate makeup, gesture and percussion tell epic stories.'], ['Mohiniyattam', 'A graceful solo tradition known for flowing movement and gentle, lyrical expression.'], ['Theyyam', 'A powerful ritual performance in northern Kerala, alive with colour, devotion and community.']] },
  { slug: 'paintings', title: 'Paintings', ml: 'ചിത്രകല', tagline: 'Sacred colour, lasting stories', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Theyyam%20performance.jpg', intro: 'Kerala mural painting turns temple walls into visual scriptures, using mineral colours, symbolic gestures and disciplined linework.', highlights: [['Kerala murals', 'Figures from Hindu mythology are rendered in warm reds, ochres, greens and deep blues.'], ['Temple tradition', 'The paintings are designed for sacred spaces and read through gesture, posture and symbol.'], ['Living practice', 'Contemporary artists continue the discipline through workshops, restoration and new commissions.']] },
  { slug: 'toys-games', title: 'Toys & Games', ml: 'കളികളും കളിപ്പാട്ടങ്ങളും', tagline: 'Play that remembers', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-fLQn67KqDuCQYBqW6sk8lTgJKeWNM6.png', intro: 'Traditional play in Kerala grows from local materials, imagination and togetherness—an invitation to learn culture by playing it.', highlights: [['Pallankuzhi', 'A counting game played with seeds or shells in a wooden board, building strategy through rhythm.'], ['Uruli and craft play', 'Small brass and wood objects echo the vessels and materials of everyday Kerala life.'], ['Team play', 'Games connected to harvest, festivals and village life make cooperation part of the fun.']] },
  { slug: 'monuments-temples', title: 'Monuments & Temples', ml: 'സ്മാരകങ്ങളും ക്ഷേത്രങ്ങളും', tagline: 'Architecture shaped by rain', image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=85', intro: 'Kerala architecture responds to monsoon, landscape and devotion with sloping roofs, courtyards, timber craft and laterite walls.', highlights: [['Sree Padmanabhaswamy Temple', 'A landmark of Thiruvananthapuram with a deep history of devotion and Dravidian forms.'], ['Vadakkunnathan Temple', 'Thrissur’s historic temple sits at the heart of the city and its festival traditions.'], ['Bekal Fort', 'A dramatic coastal fort where laterite walls meet the Arabian Sea.']] },
  { slug: 'festivals', title: 'Festivals', ml: 'ഉത്സവങ്ങൾ', tagline: 'A calendar of togetherness', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Onam%20pookalam.jpg', intro: 'Kerala’s festivals bring homes, temples, streets and waterways into one shared celebration of season, story and community.', highlights: [['Onam', 'The harvest festival is marked by pookkalams, the Onam sadya, games and the memory of Mahabali.'], ['Vishu', 'A new year tradition centred on the Vishukkani, gifting and auspicious beginnings.'], ['Thrissur Pooram', 'A spectacular temple festival known for processions, percussion and decorated elephants.']] },
  { slug: 'food', title: 'Food', ml: 'ഭക്ഷണം', tagline: 'A feast served on a leaf', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-rCmpSbBwFoNDYgMo4Cfdl4htVInqxu.png', intro: 'Kerala cuisine balances coconut, spice, sourness and sweetness, with recipes shaped by coast, harvest and the generous ritual of sharing.', highlights: [['Sadya', 'A vegetarian feast served on a banana leaf, with many small dishes arranged in a thoughtful order.'], ['Appam & puttu', 'Soft rice-based staples pair naturally with stews, kadala curry and seasonal accompaniments.'], ['Payasam', 'A festive sweet ending made in many regional styles with rice, pulses, coconut or jaggery.']] },
  { slug: 'folk-traditions', title: 'Folk Traditions & Culture', ml: 'നാടോടി പാരമ്പര്യവും സംസ്കാരവും', tagline: 'Community is the archive', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Padmanabhaswamy%20Temple.jpg', intro: 'Songs, rituals, ceremonies and shared work keep Kerala’s cultural memory active—not as a museum piece, but as a lived practice.', highlights: [['Ritual performance', 'Forms such as Theyyam connect performance, ancestry and village life in northern Kerala.'], ['Boat traditions', 'Vallam kali turns teamwork, song and water into a powerful community spectacle.'], ['Everyday heritage', 'Hospitality, craft, food and seasonal customs make culture part of daily life.']] },
  { slug: 'kerala-clothing', title: 'Kerala Traditional Clothing', ml: 'കേരളത്തിന്റെ പരമ്പരാഗത വസ്ത്രങ്ങൾ', tagline: 'Woven in cream and gold', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-pLEOtphcrocVhLPyi5FnxcRYSS0d7q.png', intro: 'Kerala’s traditional clothing is recognised for its calm palette, graceful drape and the luminous kasavu border worn for celebration and ceremony.', highlights: [['Kasavu saree', 'A cream or off-white saree finished with a characteristic golden kasavu border, especially cherished for Onam, Vishu and weddings.'], ['Mundu', 'A traditional wrapped garment worn by men, valued for its comfort, dignity and everyday cultural presence.'], ['Set mundu / Settu saree', 'A two-piece cream-and-gold ensemble related to Kerala’s saree tradition, often worn for festivals and auspicious occasions.'], ['Men’s attire', 'Mundu is commonly paired with a shirt or traditional upper garment, with ceremonial choices shaped by the occasion.'], ['Festival & ceremony', 'Onam, Vishu, weddings and temple occasions bring out the most formal cream-and-gold attire.']] },
]

const languageLabels: Record<string, string> = { English: 'English', Malayalam: 'മലയാളം', Hindi: 'हिन्दी', Tamil: 'தமிழ்', Telugu: 'తెలుగు' }

function Header({ onHome }: { onHome: () => void }) {
  const [open, setOpen] = useState(false)
  const [language, setLanguage] = useState('English')
  return <header className="site-header"><button className="brand" onClick={onHome} aria-label="Return to Kerala home"><span className="brand-mark"><Leaf size={18} /></span><span><strong>KERALA</strong><small>HERITAGE EXPLORER</small></span></button><div className="header-actions"><div className="language"><Globe2 size={16} /><select value={language} onChange={(e) => setLanguage(e.target.value)} aria-label="Choose language">{Object.keys(languageLabels).map((name) => <option key={name}>{name}</option>)}</select></div><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div>{open && <nav className="mobile-nav"><button onClick={onHome}>Explore Kerala</button><a href="#about" onClick={() => setOpen(false)}>About the archive</a></nav>}</header>
}

function Wheel({ onSelect }: { onSelect: (slug: string) => void }) {
  const radius = 190
  return <div className="wheel-wrap"><div className="wheel-orbit" aria-hidden="true" /><div className="wheel"><div className="wheel-center"><span>EXPLORE</span><strong>KERALA</strong><small>10 stories</small></div>{topics.map((topic, index) => { const angle = (index / topics.length) * Math.PI * 2 - Math.PI / 2; const x = 50 + Math.cos(angle) * 43; const y = 50 + Math.sin(angle) * 43; return <button key={topic.slug} className="wheel-topic" style={{ left: `${x}%`, top: `${y}%` }} onClick={() => onSelect(topic.slug)} aria-label={`Explore ${topic.title}`}><span className="topic-image" style={{ backgroundImage: `url(${topic.image})` }} /><span className="topic-label">{topic.title}</span></button> })}</div><div className="wheel-caption">Select a story to begin <span>→</span></div></div>
}

function Home({ onSelect }: { onSelect: (slug: string) => void }) {
  return <main className="home"><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14} /> KERALA HERITAGE ARCHIVE</p><h1>GOD&apos;S<br /><em>OWN</em><br />COUNTRY</h1><p className="hero-intro">A living archive of Kerala&apos;s heritage—where every rhythm, recipe, ritual and craft becomes an invitation to play, discover and remember.</p><button className="primary-button" onClick={() => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' })}>Begin exploring <ArrowRight size={18} /></button></div><div className="hero-art"><div className="art-card art-back" style={{ backgroundImage: `url(${topics[5].image})` }} /><div className="art-card art-main" style={{ backgroundImage: `url(${topics[2].image})` }}><span className="art-stamp">KERALA<br />CULTURE</span></div><div className="art-card art-front" style={{ backgroundImage: `url(${topics[8].image})` }} /></div></section><section id="explore" className="explore"><div className="section-heading"><div><p className="eyebrow">THE LIVING WHEEL</p><h2>Choose a thread<br /><em>of Kerala.</em></h2></div><p>Ten windows into a culture shaped by water, monsoon, devotion and the joy of gathering.</p></div><Wheel onSelect={onSelect} /></section></main>
}

type Game = { title: string; description: string; kind: 'quiz' | 'match' | 'memory' | 'select' | 'dress' | 'puzzle'; fact: string; questions?: { prompt: string; options: string[]; answer: string }[]; pairs?: [string, string][]; items?: string[]; answer?: string }

const gameImage = (slug: string) => topics.find((topic) => topic.slug === slug)?.image ?? ''
const quiz = (title: string, description: string, fact: string, questions: Game['questions']): Game => ({ title, description, fact, kind: 'quiz', questions })
const match = (title: string, description: string, fact: string, pairs: [string, string][]): Game => ({ title, description, fact, kind: 'match', pairs })

const gamesByCategory: Record<string, Game[]> = {
  'art-crafts': [match('Craft Match', 'Pair each craft with its story.', 'Aranmula Kannadi is made from a distinctive polished metal alloy.', [['Kerala Mural', 'Sacred wall painting'], ['Aranmula Kannadi', 'Handmade metal mirror'], ['Coir Craft', 'Coconut fibre craft'], ['Kasavu Weaving', 'Cream and gold textile']]), quiz('Craft Quiz', 'Test your eye for Kerala craft.', 'Craft traditions pass knowledge from hand to hand.', [{ prompt: 'Which craft is a handmade metal mirror?', options: ['Aranmula Kannadi', 'Coir Craft', 'Kasavu', 'Kathakali'], answer: 'Aranmula Kannadi' }, { prompt: 'Coir is made from which material?', options: ['Coconut fibre', 'Bamboo', 'Clay', 'Silk'], answer: 'Coconut fibre' }, { prompt: 'Murals traditionally decorate what?', options: ['Temple walls', 'Boats', 'Umbrellas', 'Drums'], answer: 'Temple walls' }, { prompt: 'Kasavu is known for its what?', options: ['Gold border', 'Blue dye', 'Mirror work', 'Feathers'], answer: 'Gold border' }, { prompt: 'Which material is common in bell-metal craft?', options: ['Metal alloy', 'Paper', 'Wool', 'Glass'], answer: 'Metal alloy' }])],
  music: [quiz('Guess the Instrument', 'Choose the instrument named by each clue.', 'Chenda ensembles give Kerala festivals their unmistakable pulse.', [{ prompt: 'The iconic cylindrical Kerala festival drum is the...', options: ['Chenda', 'Idakka', 'Maddalam', 'Nadaswaram'], answer: 'Chenda' }, { prompt: 'The hourglass-shaped drum is the...', options: ['Idakka', 'Chenda', 'Kombu', 'Veena'], answer: 'Idakka' }, { prompt: 'Which is a barrel drum?', options: ['Maddalam', 'Nadaswaram', 'Idakka', 'Kuzhal'], answer: 'Maddalam' }, { prompt: 'Which is a wind instrument?', options: ['Nadaswaram', 'Chenda', 'Maddalam', 'Idakka'], answer: 'Nadaswaram' }, { prompt: 'Temple percussion is often heard during...', options: ['Festivals', 'Silent reading', 'Painting', 'Sailing'], answer: 'Festivals' }]), match('Instrument Memory Match', 'Match four pairs of instruments.', 'Music brings temple, ritual and community into one shared rhythm.', [['Chenda', 'Chenda'], ['Idakka', 'Idakka'], ['Maddalam', 'Maddalam'], ['Nadaswaram', 'Nadaswaram']])],
  dance: [quiz('Guess the Dance', 'Identify each Kerala performance tradition.', 'Kathakali combines gesture, costume, music and epic storytelling.', [{ prompt: 'The elaborate green makeup tradition is...', options: ['Kathakali', 'Mohiniyattam', 'Theyyam', 'Thiruvathira'], answer: 'Kathakali' }, { prompt: 'The graceful solo dance is...', options: ['Mohiniyattam', 'Kathakali', 'Theyyam', 'Thiruvathira'], answer: 'Mohiniyattam' }, { prompt: 'The powerful ritual performance of northern Kerala is...', options: ['Theyyam', 'Kathakali', 'Mohiniyattam', 'Thiruvathira'], answer: 'Theyyam' }, { prompt: 'The circular women’s dance is...', options: ['Thiruvathira', 'Theyyam', 'Kathakali', 'Mohiniyattam'], answer: 'Thiruvathira' }, { prompt: 'Which tradition uses expressive mudras?', options: ['Kathakali', 'Boat racing', 'Sadya', 'Coir craft'], answer: 'Kathakali' }]), match('Dance Costume Match', 'Match each dance to its identity.', 'Kerala dance traditions are worlds of gesture, costume and story.', [['Kathakali', 'Epic dance-drama'], ['Mohiniyattam', 'Graceful solo dance'], ['Theyyam', 'Ritual performance'], ['Thiruvathira', 'Circular group dance']])],
  paintings: [quiz('Identify the Painting', 'Identify Kerala’s visual traditions.', 'Mineral colours and symbolic gestures define Kerala mural painting.', [{ prompt: 'Where are Kerala murals traditionally found?', options: ['Temple walls', 'Train stations', 'Boats', 'Markets'], answer: 'Temple walls' }, { prompt: 'A Theyyam visual is strongly associated with...', options: ['Ritual performance', 'Cooking', 'Weaving', 'Boat building'], answer: 'Ritual performance' }, { prompt: 'Kerala murals often use...', options: ['Mineral colours', 'Neon paint', 'Spray paint', 'Ink only'], answer: 'Mineral colours' }, { prompt: 'Painting stories are read through gesture and...', options: ['Symbol', 'Speed', 'Sound level', 'Weight'], answer: 'Symbol' }, { prompt: 'A mural is primarily a...', options: ['Wall painting', 'Drum', 'Garment', 'Toy'], answer: 'Wall painting' }]), { title: 'Painting Puzzle', description: 'Reconstruct a nine-piece mural.', fact: 'Kerala mural painting turns sacred walls into visual scriptures.', kind: 'puzzle' }],
  'toys-games': [match('Traditional Toy Match', 'Pair play traditions with their descriptions.', 'Traditional toys make culture tangible through local materials and imagination.', [['Pallankuzhi', 'Counting board game'], ['Wooden doll', 'Hand-carved play figure'], ['Spinning top', 'Skill and balance game'], ['Marapacha', 'Traditional wooden toy']]), { title: 'Build the Toy', description: 'Tap the pieces in order to assemble a wooden toy.', fact: 'Wooden toys connect play with Kerala’s carving traditions.', kind: 'puzzle' }],
  festivals: [quiz('Kerala Festival Quiz', 'Test your festival knowledge.', 'Festivals bring homes, temples, streets and waterways into one celebration.', [{ prompt: 'Which festival features pookkalams?', options: ['Onam', 'Vishu', 'Thrissur Pooram', 'Vallam Kali'], answer: 'Onam' }, { prompt: 'Vishukkani belongs to...', options: ['Vishu', 'Onam', 'Theyyam', 'Pooram'], answer: 'Vishu' }, { prompt: 'Decorated elephants are iconic at...', options: ['Thrissur Pooram', 'Vishu', 'Onam', 'Vallam Kali'], answer: 'Thrissur Pooram' }, { prompt: 'Vallam Kali is a...', options: ['Boat race', 'Dance', 'Feast', 'Painting'], answer: 'Boat race' }, { prompt: 'Onam is associated with the memory of...', options: ['Mahabali', 'Arjuna', 'Ashoka', 'Shiva'], answer: 'Mahabali' }]), match('Festival Image Match', 'Match each celebration with its marker.', 'Onam, Vishu, Pooram and boat races make Kerala’s calendar communal.', [['Onam', 'Pookkalam and sadya'], ['Vishu', 'Vishukkani'], ['Thrissur Pooram', 'Percussion and elephants'], ['Vallam Kali', 'Snake boat race']])],
  food: [{ title: 'Build a Kerala Sadya', description: 'Select the dishes that belong on a sadya leaf.', fact: 'A sadya is a thoughtful vegetarian feast served on a banana leaf.', kind: 'select', items: ['Rice', 'Sambar', 'Avial', 'Thoran', 'Olan', 'Pachadi', 'Payasam', 'Pizza', 'Noodles', 'Tacos'], answer: 'Rice|Sambar|Avial|Thoran|Olan|Pachadi|Payasam' }, quiz('Guess the Kerala Food', 'Identify each dish from its clue.', 'Kerala cuisine balances coconut, spice, sourness and sweetness.', [{ prompt: 'Steamed cylinders of rice and coconut are...', options: ['Puttu', 'Appam', 'Avial', 'Payasam'], answer: 'Puttu' }, { prompt: 'Lacy fermented rice pancakes are...', options: ['Appam', 'Puttu', 'Thoran', 'Chips'], answer: 'Appam' }, { prompt: 'A festive sweet dish is...', options: ['Payasam', 'Avial', 'Sambar', 'Pachadi'], answer: 'Payasam' }, { prompt: 'A mixed vegetable dish with coconut is...', options: ['Avial', 'Appam', 'Puttu', 'Banana chips'], answer: 'Avial' }, { prompt: 'A crisp snack often made from plantain is...', options: ['Banana chips', 'Olan', 'Payasam', 'Rice'], answer: 'Banana chips' }])],
  'folk-traditions': [quiz('Kerala Heritage Quiz', 'Explore places, rituals and shared traditions.', 'Culture stays alive when communities practice and pass it on.', [{ prompt: 'Which temple is in Thiruvananthapuram?', options: ['Sree Padmanabhaswamy Temple', 'Meenakshi Temple', 'Konark Temple', 'Brihadeeswarar Temple'], answer: 'Sree Padmanabhaswamy Temple' }, { prompt: 'Theyyam is a...', options: ['Ritual performance', 'Sweet', 'Garment', 'Boat'], answer: 'Ritual performance' }, { prompt: 'Vallam Kali uses...', options: ['Snake boats', 'Elephants', 'Bicycles', 'Camels'], answer: 'Snake boats' }, { prompt: 'Kerala architecture responds especially to...', options: ['Monsoon', 'Desert heat', 'Snow', 'Tundra'], answer: 'Monsoon' }, { prompt: 'Hospitality is an example of...', options: ['Everyday heritage', 'A musical scale', 'A mural pigment', 'A toy'], answer: 'Everyday heritage' }]), match('Heritage Match', 'Match each cultural image to its description.', 'Songs, rituals and shared work keep Kerala’s cultural memory active.', [['Sree Padmanabhaswamy Temple', 'Thiruvananthapuram landmark'], ['Theyyam', 'Northern ritual performance'], ['Vallam Kali', 'Community boat tradition'], ['Kerala architecture', 'Sloping roofs and courtyards']])],
  'kerala-clothing': [{ title: 'Dress the Character', description: 'Assemble a classic cream-and-gold look.', fact: 'The kasavu border is cherished for festivals, weddings and ceremony.', kind: 'dress', items: ['Kasavu saree', 'Traditional blouse', 'Gold accessories'] }, quiz('Clothing Quiz', 'Test your knowledge of Kerala attire.', 'Kerala clothing is known for a calm palette, graceful drape and kasavu border.', [{ prompt: 'What characterises a Kasavu saree?', options: ['Gold border', 'Mirror work', 'Floral print', 'Heavy embroidery'], answer: 'Gold border' }, { prompt: 'Mundu is traditionally worn as a...', options: ['Wrapped garment', 'Necklace', 'Hat', 'Shoe'], answer: 'Wrapped garment' }, { prompt: 'Kerala wedding attire often uses...', options: ['Cream and gold', 'Neon green', 'Denim', 'Plaid'], answer: 'Cream and gold' }, { prompt: 'Kasavu is especially associated with...', options: ['Onam', 'Holi', 'Christmas', 'Baisakhi'], answer: 'Onam' }, { prompt: 'A set mundu is a...', options: ['Two-piece ensemble', 'Drum', 'Painting', 'Sweet'], answer: 'Two-piece ensemble' }])]
}

function GamePlay({ game, onBack }: { game: Game; onBack: () => void }) {
  const [step, setStep] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<string[]>([]); const [feedback, setFeedback] = useState(''); const [done, setDone] = useState(false)
  const total = game.kind === 'quiz' ? game.questions?.length ?? 0 : game.kind === 'match' || game.kind === 'memory' ? game.pairs?.length ?? 0 : game.kind === 'select' ? game.answer?.split('|').length ?? 0 : game.kind === 'dress' ? game.items?.length ?? 0 : 1
  const reset = () => { setStep(0); setScore(0); setSelected([]); setFeedback(''); setDone(false) }
  const finish = (nextScore = score) => { setScore(nextScore); setDone(true) }
  const answerQuiz = (answer: string) => { if (feedback) return; const correct = answer === game.questions?.[step]?.answer; const nextScore = score + (correct ? 1 : 0); setScore(nextScore); setFeedback(correct ? 'Correct!' : `Not quite — the answer is ${game.questions?.[step]?.answer}.`); setTimeout(() => { setFeedback(''); if (step + 1 >= total) finish(nextScore); else setStep(step + 1) }, 650) }
  const choose = (item: string) => { if (selected.includes(item)) return; const next = [...selected, item]; setSelected(next); if (game.kind === 'select') { const correct = game.answer?.split('|').includes(item); setScore(score + (correct ? 1 : 0)); } if (next.length >= (game.kind === 'dress' ? total : game.kind === 'select' ? 7 : game.kind === 'puzzle' ? 9 : total)) finish(game.kind === 'select' ? next.filter((x) => game.answer?.split('|').includes(x)).length : next.length) }
  return <section className="game-screen"><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> Back to Games</button>{done ? <div className="game-result"><p className="eyebrow">GAME COMPLETE!</p><h2>Score: {score} / {total}</h2><p>{game.fact}</p><div className="game-actions"><button className="primary-button" onClick={reset}>Play Again</button><button className="secondary-button" onClick={onBack}>Choose Another Game</button></div></div> : <><p className="eyebrow">{game.title}</p><h2>{game.description}</h2>{game.kind === 'quiz' && <div className="quiz-box"><p>Question {step + 1} / {total}</p><h3>{game.questions?.[step].prompt}</h3><div className="option-grid">{game.questions?.[step].options.map((option) => <button key={option} className="game-option" onClick={() => answerQuiz(option)}>{option}</button>)}</div>{feedback && <strong className={feedback === 'Correct!' ? 'correct' : 'incorrect'}>{feedback}</strong>}</div>}{(game.kind === 'match' || game.kind === 'memory') && <div className="match-box"><p>Match each item to its meaning.</p><div className="option-grid">{game.pairs?.map(([a, b]) => <button key={a} className={`game-option ${selected.includes(a) ? 'selected' : ''}`} onClick={() => choose(a)} disabled={selected.includes(a)}>{selected.includes(a) ? `${a} — ${b}` : a}</button>)}</div></div>}{game.kind === 'select' && <div className="match-box"><p>Select the seven dishes that belong in a sadya.</p><div className="option-grid">{game.items?.map((item) => <button key={item} className={`game-option ${selected.includes(item) ? 'selected' : ''}`} onClick={() => choose(item)}>{item}</button>)}</div><button className="primary-button" onClick={() => finish(selected.filter((x) => game.answer?.split('|').includes(x)).length)}>Serve Sadya</button></div>}{game.kind === 'dress' && <div className="match-box"><p>Choose every piece to complete the look.</p><div className="option-grid">{game.items?.map((item) => <button key={item} className={`game-option ${selected.includes(item) ? 'selected' : ''}`} onClick={() => choose(item)}>{item}</button>)}</div></div>}{game.kind === 'puzzle' && <div className="puzzle-box"><div className="puzzle-image" style={{ backgroundImage: `url(${gameImage('paintings')})` }} /><p>Arrange the nine tiles by tapping them in sequence.</p><div className="puzzle-grid">{Array.from({ length: 9 }, (_, i) => <button key={i} className="game-option" onClick={() => choose(String(i))}>{i + 1}</button>)}</div></div>}</>}</section>
}

function GameHub({ topic, onClose }: { topic: typeof topics[number]; onClose: () => void }) {
  const games = gamesByCategory[topic.slug] ?? []; const [active, setActive] = useState<Game | null>(null)
  return <section className="game-hub">{active ? <GamePlay game={active} onBack={() => setActive(null)} /> : <><button className="back-link" onClick={onClose}><ArrowLeft size={16} /> Back to story</button><p className="eyebrow">PLAY GAMES</p><h2>Kerala {topic.title} Games</h2><div className="game-card-grid">{games.map((game, i) => <article className="game-card" key={game.title}><span>GAME {i + 1}</span><h3>{game.title}</h3><p>{game.description}</p><button className="primary-button" onClick={() => setActive(game)}>Play</button></article>)}</div></>}</section>
}

function TopicPage({ topic, index, onHome, onSelect }: { topic: typeof topics[number], index: number, onHome: () => void, onSelect: (slug: string) => void }) {
  const previous = topics[(index - 1 + topics.length) % topics.length]; const next = topics[(index + 1) % topics.length]; const [showGames, setShowGames] = useState(false)
  return <main className="topic-page"><button className="back-link" onClick={onHome}><ArrowLeft size={16} /> Back to the wheel</button>{showGames ? <GameHub topic={topic} onClose={() => setShowGames(false)} /> : <><section className="topic-hero"><div className="topic-hero-image" style={{ backgroundImage: `url(${topic.image})` }}><span className="topic-number">{String(index + 1).padStart(2, '0')} / 10</span></div><div className="topic-heading"><p className="eyebrow">{topic.ml}</p><p className="topic-tagline">{topic.tagline}</p><h1>{topic.title}</h1><p className="topic-intro">{topic.intro}</p><button className="primary-button" onClick={() => setShowGames(true)}>Play Games <ArrowRight size={18} /></button></div></section><section className="highlights"><p className="eyebrow">DISCOVER MORE</p><div className="highlight-grid">{topic.highlights.map(([title, text], i) => <article className="highlight-card" key={title}><span>0{i + 1}</span><h2>{title}</h2><p>{text}</p></article>)}</div></section><nav className="topic-nav" aria-label="Topic navigation"><button onClick={() => onSelect(previous.slug)}><ArrowLeft size={18} /><span><small>Previous story</small>{previous.title}</span></button><button onClick={() => onSelect(next.slug)}><span><small>Next story</small>{next.title}</span><ArrowRight size={18} /></button></nav></>}</main>
}

export default function KeralaExplorer() {
  const [path, setPath] = useState('/')
  useEffect(() => {
    const syncPath = () => setPath(window.location.pathname)
    syncPath()
    window.addEventListener('popstate', syncPath)
    return () => window.removeEventListener('popstate', syncPath)
  }, [])
  const selectedSlug = path.startsWith('/explore/') ? path.replace('/explore/', '') : ''
  const selected = useMemo(() => topics.find((topic) => topic.slug === selectedSlug), [selectedSlug])
  const navigate = (slug: string) => { const nextPath = `/explore/${slug}`; window.history.pushState({}, '', nextPath); setPath(nextPath); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const home = () => { window.history.pushState({}, '', '/'); setPath('/'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="app-shell"><Header onHome={home} />{selected ? <TopicPage topic={selected} index={topics.indexOf(selected)} onHome={home} onSelect={navigate} /> : <Home onSelect={navigate} />}<footer><span>KERALA HERITAGE EXPLORER</span><span>Made for curious minds</span></footer></div>
}

export { topics }
